<?php

namespace Ethernick\ActivityPubCore\Tests;

use Statamic\Facades\Entry;
use Tests\TestCase;

/**
 * Tests that ActivityPub JSON is correctly generated and accessible for entries.
 * 
 * NOTE: These tests verify the JSON generation pipeline (Listener -> activitypub_json field)
 * rather than Statamic's front-end collection routing, which requires Antlers rendering 
 * that isn't available in the test environment. The NegotiateActivityPubResponse middleware
 * is tested implicitly by ActorTemplateOverrideTest which uses a custom web route.
 */
class IdAccessibilityTest extends TestCase
{
    protected $actorId;

    protected function setUp(): void
    {
        parent::setUp();

        // Create Actor in sandbox
        $actor = Entry::make()->collection('actors')->slug('ethernick')->data(['title' => 'Nick', 'is_internal' => true])->published(true);
        $actor->save();
        $this->actorId = $actor->id();

        // Ensure settings exist in sandbox
        file_put_contents(
            \Ethernick\ActivityPubCore\Services\ActivityPubUtils::settingsPath(),
            "notes:\n  enabled: true\n  type: Note\n  federated: true\nactivities:\n  enabled: true\n  type: Activity\n  federated: true\n"
        );
    }

    protected function tearDown(): void
    {
        parent::tearDown();
    }

    public function test_note_url_returns_activitypub_json()
    {
        // 1. Create Internal Note — the listener should auto-generate activitypub_json
        $note = Entry::make()
            ->collection('notes')
            ->slug('test-note-json')
            ->data([
                'content' => 'Testing JSON Response',
                'actor' => [$this->actorId],
                'is_internal' => true,
            ]);
        $note->save();

        // Re-fetch to get listener-generated fields
        $note = Entry::find($note->id());

        // 2. Verify activitypub_json was generated
        $apJson = $note->get('activitypub_json');
        $this->assertNotEmpty($apJson, 'activitypub_json should be generated by the listener');

        // 3. Verify it's valid JSON with correct type
        $json = is_string($apJson) ? json_decode($apJson, true) : $apJson;
        $this->assertIsArray($json, 'activitypub_json should decode to an array');
        $this->assertEquals('Note', $json['type']);

        // 4. Verify the entry has a resolvable URL
        $url = $note->url();
        $this->assertNotNull($url, 'Note should have a URL from collection route');
        $this->assertStringContainsString($note->slug(), $url);

        // 5. Verify the JSON 'id' field matches the entry's absolute URL
        $absUrl = $note->absoluteUrl();
        $this->assertNotNull($absUrl, 'Note should have an absolute URL');
        $this->assertEquals($absUrl, $json['id']);
    }

    public function test_activity_url_returns_activitypub_json()
    {
        // 1. Create Internal Activity
        $activity = Entry::make()
            ->collection('activities')
            ->slug('test-activity-json')
            ->data([
                'type' => 'Create',
                'actor' => [$this->actorId],
                'related_object' => 'https://example.com/note/1',
                'is_internal' => true,
            ]);
        $activity->save();

        // Re-fetch to get listener-generated fields
        $activity = Entry::find($activity->id());

        // 2. Verify activitypub_json was generated
        $apJson = $activity->get('activitypub_json');
        $this->assertNotEmpty($apJson, 'activitypub_json should be generated by the listener');

        // 3. Verify it's valid JSON with correct type
        $json = is_string($apJson) ? json_decode($apJson, true) : $apJson;
        $this->assertIsArray($json, 'activitypub_json should decode to an array');
        $this->assertEquals('Create', $json['type']);

        // 4. Verify the entry has a resolvable URL
        $url = $activity->url();
        $this->assertNotNull($url, 'Activity should have a URL from collection route');
        $this->assertStringContainsString($activity->slug(), $url);

        // 5. Verify the JSON 'id' field matches the entry's absolute URL
        $absUrl = $activity->absoluteUrl();
        $this->assertNotNull($absUrl, 'Activity should have an absolute URL');
        $this->assertEquals($absUrl, $json['id']);
    }
}
